# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('phone', models.CharField(max_length=128, verbose_name='Phone number')),
                ('promo', models.CharField(max_length=128, verbose_name='Promo-code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('note', models.TextField(blank=True, verbose_name='Приміткм')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Неоформлена', max_length=128, null=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус замовлення',
                'verbose_name_plural': 'Статуси замовлень',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xhose.Status', verbose_name='Статус'),
        ),
    ]
