# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xhose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Приміткм'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=128, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='promo',
            field=models.CharField(max_length=128, null=True, verbose_name='Promo-code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xhose.Status', verbose_name='Статус'),
        ),
    ]
